// lib/features/zara_engine/models/zara_state.dart
// Z.A.R.A. — Immutable State Model
// ✅ Real Device Metrics • Security Alerts • Code Analysis • Automation Tasks
// ✅ CopyWith Pattern • Null Safety • Production-Ready

import 'package:battery_plus/battery_plus.dart';
import '../../../core/enums/mood_enum.dart';

/// Immutable state model for Z.A.R.A. controller
/// Uses copyWith pattern for efficient state updates
class ZaraState {
  // ========== Core State ==========
  
  /// Whether Z.A.R.A. is currently active/engaged
  final bool isActive;
  
  /// Current emotional state (affects UI, dialogue, animations)
  final Mood mood;
  
  /// Last user command received
  final String lastCommand;
  
  /// Last response generated by Z.A.R.A.
  final String lastResponse;
  
  /// Timestamp of last user interaction
  final DateTime lastActivity;
  
  // ========== Animation State ==========
  
  /// Pulse animation progress (0.0 to 1.0) — for breathing orb effect
  final double pulseProgress;
  
  /// Current orb scale multiplier (1.0 to 1.15) — for breathing animation
  final double orbScale;
  
  /// Glow intensity (0.0 to 1.0) — for visual effects
  final double glowIntensity;
  
  // ========== Affection/Personality ==========
  
  /// Affection level (0-100) — affects mood transitions and dialogue tone
  final int affectionLevel;
  
  /// Dialogue history (last 10 messages) — for context-aware responses
  final List<String> dialogueHistory;
  
  // ========== REAL Device Metrics ==========
  
  /// Real battery percentage from battery_plus (0-100)
  final int batteryLevel;
  
  /// Real battery state from battery_plus (charging, full, discharging, etc.)
  final BatteryState batteryState;
  
  /// Real device model from device_info_plus (e.g., "SM-G998B")
  final String deviceModel;
  
  /// Real Android version from device_info_plus (e.g., "14")
  final String androidVersion;
  
  /// Real WiFi connectivity status from connectivity_plus
  final bool isWifiConnected;
  
  /// Real mobile data connectivity status from connectivity_plus
  final bool isMobileConnected;
  
  /// Real device temperature (if sensor available, else null)
  final double? deviceTemperature;
  
  /// Real available storage in MB from path_provider
  final int availableStorageMB;
  
  /// Real total storage in MB from path_provider
  final int totalStorageMB;
  
  // ========== Calculated Metrics ==========
  
  /// Calculated system integrity (0-100) based on battery, storage, security
  double get calculatedIntegrity {
    double integrity = 100.0;
    
    // Battery health factor
    if (batteryLevel < 20) integrity -= 15;
    else if (batteryLevel < 50) integrity -= 5;
    
    // Storage health factor
    if (totalStorageMB > 0) {
      final usedPercent = ((totalStorageMB - availableStorageMB) / totalStorageMB) * 100;
      if (usedPercent > 90) integrity -= 20;
      else if (usedPercent > 80) integrity -= 10;
    }
    
    // Security factor
    if (wrongPasswordAttempts > 2) integrity -= 15;
    if (securityAlerts.isNotEmpty) {
      integrity -= (securityAlerts.length * 3).clamp(0, 30);
    }
    
    // Network factor
    if (!isWifiConnected && !isMobileConnected) integrity -= 10;
    
    return integrity.clamp(0, 100);
  }
  
  // ========== Guardian/Security State ==========
  
  /// Whether Guardian Mode (anti-theft) is active
  final bool isGuardianActive;
  
  /// Count of wrong password attempts (for theatrical security)
  final int wrongPasswordAttempts;
  
  /// List of security alerts (intruder, overheat, etc.)
  final List<SecurityAlert> securityAlerts;
  
  /// Path to last captured intruder photo (if any)
  final String? lastIntruderPhotoPath;
  
  /// Timestamp of last security check
  final DateTime? lastSecurityCheck;
  
  // ========== Code Analysis State ==========
  
  /// Code currently being analyzed (if any)
  final String? codeUnderAnalysis;
  
  /// Result of last code analysis
  final CodeAnalysisResult? codeAnalysisResult;
  
  // ========== Automation State ==========
  
  /// List of active automation tasks
  final List<AutomationTask> automationTasks;
  
  /// Count of completed automation tasks (session)
  final int completedTasks;
  
  // ========== Constructor ==========
  
  const ZaraState({
    required this.isActive,
    required this.mood,
    required this.lastCommand,
    required this.lastResponse,
    required this.lastActivity,
    required this.pulseProgress,
    required this.orbScale,
    required this.glowIntensity,
    required this.affectionLevel,
    required this.dialogueHistory,
    required this.batteryLevel,
    required this.batteryState,
    required this.deviceModel,
    required this.androidVersion,
    required this.isWifiConnected,
    required this.isMobileConnected,
    this.deviceTemperature,
    required this.availableStorageMB,
    required this.totalStorageMB,
    required this.isGuardianActive,
    required this.wrongPasswordAttempts,
    required this.securityAlerts,
    this.lastIntruderPhotoPath,
    this.lastSecurityCheck,
    this.codeUnderAnalysis,
    this.codeAnalysisResult,
    required this.automationTasks,
    required this.completedTasks,
  });

  // ========== Factory: Initial State ==========
  
  /// Create initial state with default values
  factory ZaraState.initial() => ZaraState(
    // Core
    isActive: false,
    mood: Mood.calm,
    lastCommand: '',
    lastResponse: '',
    lastActivity: DateTime.now(),
    
    // Animation
    pulseProgress: 0,
    orbScale: 1.0,
    glowIntensity: 0.3,
    
    // Affection
    affectionLevel: 75,
    dialogueHistory: [],
    
    // Device Metrics (defaults)
    batteryLevel: 100,
    batteryState: BatteryState.full,
    deviceModel: 'Unknown',
    androidVersion: 'Unknown',
    isWifiConnected: false,
    isMobileConnected: false,
    deviceTemperature: null,
    availableStorageMB: 0,
    totalStorageMB: 0,
    
    // Guardian
    isGuardianActive: false,
    wrongPasswordAttempts: 0,
    securityAlerts: [],
    lastIntruderPhotoPath: null,
    lastSecurityCheck: null,
    
    // Code Analysis
    codeUnderAnalysis: null,
    codeAnalysisResult: null,
    
    // Automation
    automationTasks: [],
    completedTasks: 0,
  );

  // ========== copyWith Pattern ==========
  
  /// Create a new state with updated fields (immutable update pattern)
  ZaraState copyWith({
    bool? isActive,
    Mood? mood,
    String? lastCommand,
    String? lastResponse,
    DateTime? lastActivity,
    double? pulseProgress,
    double? orbScale,
    double? glowIntensity,
    int? affectionLevel,
    List<String>? dialogueHistory,
    int? batteryLevel,
    BatteryState? batteryState,
    String? deviceModel,
    String? androidVersion,
    bool? isWifiConnected,
    bool? isMobileConnected,
    double? deviceTemperature,
    int? availableStorageMB,
    int? totalStorageMB,
    bool? isGuardianActive,
    int? wrongPasswordAttempts,
    List<SecurityAlert>? securityAlerts,
    String? lastIntruderPhotoPath,
    DateTime? lastSecurityCheck,
    String? codeUnderAnalysis,
    CodeAnalysisResult? codeAnalysisResult,
    List<AutomationTask>? automationTasks,
    int? completedTasks,
  }) {
    return ZaraState(
      // Core
      isActive: isActive ?? this.isActive,
      mood: mood ?? this.mood,
      lastCommand: lastCommand ?? this.lastCommand,
      lastResponse: lastResponse ?? this.lastResponse,
      lastActivity: lastActivity ?? this.lastActivity,
      
      // Animation
      pulseProgress: pulseProgress ?? this.pulseProgress,
      orbScale: orbScale ?? this.orbScale,
      glowIntensity: glowIntensity ?? this.glowIntensity,
      
      // Affection
      affectionLevel: affectionLevel ?? this.affectionLevel,
      dialogueHistory: dialogueHistory ?? this.dialogueHistory,
      
      // Device Metrics
      batteryLevel: batteryLevel ?? this.batteryLevel,
      batteryState: batteryState ?? this.batteryState,
      deviceModel: deviceModel ?? this.deviceModel,
      androidVersion: androidVersion ?? this.androidVersion,
      isWifiConnected: isWifiConnected ?? this.isWifiConnected,
      isMobileConnected: isMobileConnected ?? this.isMobileConnected,
      deviceTemperature: deviceTemperature ?? this.deviceTemperature,
      availableStorageMB: availableStorageMB ?? this.availableStorageMB,
      totalStorageMB: totalStorageMB ?? this.totalStorageMB,
      
      // Guardian
      isGuardianActive: isGuardianActive ?? this.isGuardianActive,
      wrongPasswordAttempts: wrongPasswordAttempts ?? this.wrongPasswordAttempts,
      securityAlerts: securityAlerts ?? this.securityAlerts,
      lastIntruderPhotoPath: lastIntruderPhotoPath ?? this.lastIntruderPhotoPath,
      lastSecurityCheck: lastSecurityCheck ?? this.lastSecurityCheck,
      
      // Code Analysis
      codeUnderAnalysis: codeUnderAnalysis ?? this.codeUnderAnalysis,
      codeAnalysisResult: codeAnalysisResult ?? this.codeAnalysisResult,
      
      // Automation
      automationTasks: automationTasks ?? this.automationTasks,
      completedTasks: completedTasks ?? this.completedTasks,
    );
  }

  // ========== Utility Methods ==========
  
  /// Check if state has any active security alerts
  bool get hasSecurityAlerts => securityAlerts.isNotEmpty;
  
  /// Check if any automation tasks are running
  bool get hasActiveTasks => 
      automationTasks.any((t) => t.status == TaskStatus.running);
  
  /// Get count of pending automation tasks
  int get pendingTaskCount => 
      automationTasks.where((t) => t.status == TaskStatus.pending).length;
  
  /// Check if code analysis is in progress
  bool get isAnalyzingCode => codeUnderAnalysis != null;
  
  /// Get formatted storage info (e.g., "45.2 GB / 128 GB")
  String get formattedStorage {
    if (totalStorageMB == 0) return 'Unknown';
    final usedGB = (totalStorageMB - availableStorageMB) / 1024;
    final totalGB = totalStorageMB / 1024;
    return '${usedGB.toStringAsFixed(1)} GB / ${totalGB.toStringAsFixed(1)} GB';
  }
  
  /// Get battery status emoji + text
  String get batteryStatusText {
    if (batteryLevel <= 10) return '🪫 Critical';
    if (batteryLevel <= 20) return '🔋 Low';
    if (batteryState == BatteryState.charging) return '⚡ Charging';
    if (batteryState == BatteryState.full) return '✓ Full';
    return '🔋 ${batteryLevel}%';
  }
}

// ========== Security Alert Model ==========

/// Represents a security event in Guardian Mode
class SecurityAlert {
  /// Unique identifier for this alert
  final String id;
  
  /// Type of security event (intruder, overheat, etc.)
  final AlertType type;
  
  /// Human-readable message for display
  final String message;
  
  /// Timestamp when alert was triggered
  final DateTime timestamp;
  
  /// Whether alert has been resolved/dismissed
  final bool isResolved;
  
  /// Path to captured intruder photo (if applicable)
  final String? photoPath;
  
  /// GPS coordinates or location description (if applicable)
  final String? locationData;
  
  /// Additional metadata (JSON-serializable)
  final Map<String, dynamic>? metadata;

  const SecurityAlert({
    required this.id,
    required this.type,
    required this.message,
    required this.timestamp,
    this.isResolved = false,
    this.photoPath,
    this.locationData,
    this.metadata,
  });

  /// Check if alert has expired (older than 24 hours)
  bool get isExpired => 
      DateTime.now().difference(timestamp) > const Duration(hours: 24);
  
  /// Create a copy with updated fields
  SecurityAlert copyWith({
    bool? isResolved,
    String? photoPath,
    String? locationData,
    Map<String, dynamic>? metadata,
  }) {
    return SecurityAlert(
      id: id,
      type: type,
      message: message,
      timestamp: timestamp,
      isResolved: isResolved ?? this.isResolved,
      photoPath: photoPath ?? this.photoPath,
      locationData: locationData ?? this.locationData,
      metadata: metadata ?? this.metadata,
    );
  }
}

/// Types of security alerts
enum AlertType {
  /// Unauthorized access attempt detected
  intruderDetected,
  
  /// Unusual app installation or permission change
  unusualActivity,
  
  /// Device moved from safe location zone
  locationChange,
  
  /// Suspicious WiFi network detected
  networkThreat,
  
  /// Device temperature above safe threshold
  overheating,
  
  /// Storage usage critically high
  storageCritical,
  
  /// Battery critically low
  batteryCritical,
  
  /// Important permission was revoked
  permissionRevoked,
  
  /// Custom/unknown alert type
  other,
}

// ========== Code Analysis Result Model ==========

/// Result of code analysis operation
class CodeAnalysisResult {
  /// Whether code passed all checks
  final bool isValid;
  
  /// List of detected issues (syntax errors, warnings, suggestions)
  final List<CodeIssue> issues;
  
  /// Human-readable suggestions for improvement
  final List<String> suggestions;
  
  /// Total lines of code analyzed
  final int lineCount;
  
  /// Total characters in analyzed code
  final int characterCount;
  
  /// Map of class names to occurrence counts
  final Map<String, int> classCount;
  
  /// Map of function names to occurrence counts
  final Map<String, int> functionCount;

  const CodeAnalysisResult({
    required this.isValid,
    required this.issues,
    required this.suggestions,
    required this.lineCount,
    required this.characterCount,
    required this.classCount,
    required this.functionCount,
  });

  /// Get count of errors (non-warning issues)
  int get errorCount => 
      issues.where((i) => i.type == IssueType.syntaxError).length;
  
  /// Get count of warnings (non-error issues)
  int get warningCount => 
      issues.where((i) => i.type != IssueType.syntaxError).length;
}

/// Represents a single code issue found during analysis
class CodeIssue {
  /// Type/category of the issue
  final IssueType type;
  
  /// Human-readable description of the issue
  final String message;
  
  /// Line number where issue was found (0 if unknown)
  final int line;
  
  /// Column number where issue was found (0 if unknown)
  final int column;
  
  /// Suggested fix or improvement (if available)
  final String? suggestion;

  const CodeIssue({
    required this.type,
    required this.message,
    required this.line,
    required this.column,
    this.suggestion,
  });
}

/// Categories of code issues
enum IssueType {
  /// Syntax error — code won't compile
  syntaxError,
  
  /// Unused import statement
  unusedImport,
  
  /// Variable declared but never used
  unusedVariable,
  
  /// Function missing return statement
  missingReturn,
  
  /// Type mismatch or inference issue
  typeMismatch,
  
  /// Null safety violation
  nullSafety,
  
  /// Performance concern (e.g., unnecessary rebuilds)
  performance,
  
  /// Style guide violation
  style,
  
  /// Security concern (e.g., hardcoded secrets)
  security,
}

// ========== Automation Task Model ==========

/// Represents an automation task in execution queue
class AutomationTask {
  /// Unique identifier for this task
  final String id;
  
  /// Human-readable description of what task does
  final String description;
  
  /// Category/type of task (for routing execution logic)
  final TaskType type;
  
  /// Current execution status
  final TaskStatus status;
  
  /// When task was created/queued
  final DateTime createdAt;
  
  /// When task completed (if finished)
  final DateTime? completedAt;
  
  /// Error message if task failed
  final String? errorMessage;

  const AutomationTask({
    required this.id,
    required this.description,
    required this.type,
    this.status = TaskStatus.pending,
    required this.createdAt,
    this.completedAt,
    this.errorMessage,
  });

  /// Create a copy with updated fields
  AutomationTask copyWith({
    TaskStatus? status,
    DateTime? completedAt,
    String? errorMessage,
  }) {
    return AutomationTask(
      id: id,
      description: description,
      type: type,
      status: status ?? this.status,
      createdAt: createdAt,
      completedAt: completedAt ?? this.completedAt,
      errorMessage: errorMessage ?? this.errorMessage,
    );
  }
  
  /// Check if task is currently executing
  bool get isRunning => status == TaskStatus.running;
  
  /// Check if task has finished (success or failure)
  bool get isFinished => 
      status == TaskStatus.completed || status == TaskStatus.failed;
}

/// Categories of automation tasks
enum TaskType {
  /// Change system setting (brightness, volume, etc.)
  systemSetting,
  
  /// Launch an application
  appLaunch,
  
  /// Send a message (SMS, WhatsApp, etc.)
  messageSend,
  
  /// File operation (save, delete, move)
  fileOperation,
  
  /// Network action (toggle WiFi, mobile data)
  networkAction,
  
  /// Camera action (take photo, record video)
  cameraAction,
  
  /// Send an email
  emailSend,
  
  /// Share current location
  locationShare,
  
  /// Custom/other task type
  other,
}

/// Execution status of automation tasks
enum TaskStatus {
  /// Task is queued, waiting to execute
  pending,
  
  /// Task is currently executing
  running,
  
  /// Task completed successfully
  completed,
  
  /// Task failed with error
  failed,
  
  /// Task was cancelled by user
  cancelled,
}
